USE [db01]
GO
CREATE SCHEMA [HR]
GO
CREATE TABLE HR.Department
	(
	id int NOT NULL,
	name nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE HR.Department ADD CONSTRAINT
	PK_Department PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO