USE master;
IF EXISTS(SELECT * FROM sys.databases WHERE name = 'db01')
BEGIN
	ALTER DATABASE db01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE db01;
END
GO

CREATE DATABASE [db01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db01', FILENAME = N'C:\SQLData\db01.mdf' , SIZE = 8192KB , FILEGROWTH = 4096KB )
 LOG ON 
( NAME = N'db01_log', FILENAME = N'C:\SQLData\db01_log.ldf' , SIZE = 8192KB , FILEGROWTH = 4096KB )
GO

USE db01;

CREATE TABLE dbo.BigTable
(
id int IDENTITY(1, 1) PRIMARY KEY,
big_data nchar(4000)
);
GO
--Ctrl + Shift + R
INSERT INTO dbo.BigTable DEFAULT VALUES;
GO 4096
--32MB+4MB = 36MB => 36864KB
SELECT 36 * 1024 

INSERT INTO dbo.BigTable DEFAULT VALUES;
GO 2048

DELETE FROM dbo.BigTable;
GO

DBCC SHRINKDATABASE(N'db01' )
GO
